package idv.jack;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@SpringBootApplication
public class HelloWorld10k {
    @RestController
    class ColdStartController10k {
        @GetMapping("/hello10k")
        String hello() {
            return "Hello Java, For the cold start test.";
        }
    }

    /*public static void main(String[] args) {
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        System.out.println("Hello Java, For the cold start test.");
        SpringApplication.run(HelloWorld10k.class, args);
    }*/
}
