apiVersion: v1
kind: PersistentVolume
metadata:
  name: fission-pv
spec:
  capacity:
    storage: 8Gi
  storageClassName: "local-storage"
  accessModes:
  - ReadWriteOnce
  claimRef:
    name: fission-storage-pvc
    namespace: fission
  local:
    path: /home/user1/storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-master
